# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: kondratyev.d.95@gmail.com
author_name: Dmitry Kondratyev
data_format: string
file_extension: ''
has_binder: false
has_settings: true
kind: frontend
labextension_name: jupyterlab-iframe-launcher
mimetype: ''
mimetype_name: ''
project_short_description: Adds a custom iframe item that opens an iframe when clicked.
python_name: jupyterlab_iframe_launcher
repository: ''
test: false
viewer_name: ''

