# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: kondratyev.d.95@gmail.com
author_name: Dmitry Kondratyev
data_format: string
file_extension: ''
has_binder: false
has_settings: false
kind: frontend
labextension_name: jupyterlab-shutdown
mimetype: ''
mimetype_name: ''
project_short_description: Adds a button that shuts down Jupyter server
python_name: jupyterlab_shutdown
repository: ''
test: false
viewer_name: ''

